name: Continuous Integration

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  rspec:
    name: Run RSpec Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0

    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3

    - name: Check PostgreSQL Service
      run: |
        service postgresql status

    - name: Connect to PostgreSQL
      run: |
        rails db:schema:load

    - name: Run RSpec tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rspec
